backup: true # make a copy of playerTable in MineProfession/backup when saving the table
auto-save-cycle: 86400 # the cycle time of saving player data (unit: second) 
minor-require: 30 # the required level of major profession to have a minor profession
max-major-level: 85 # the maximum level of major profession
max-minor-level: 85 #the maximum level of minor profession
track-placement: [CLAY, LOG, LEAVES, PUMPKIN, MELON_BLOCK, SUGAR_CANE_BLOCK, IRON_ORE, GOLD_ORE, COAL_ORE, REDSTONE_ORE, GLOWING_REDSTONE_ORE, LAPIS_ORE, GOLD_ORE, DIAMOND_ORE]
power-formula: 1-Math.cos(level*Math.PI/maxLevel/2) # the power of profession, have to be in [0,1], maxLevel = max(max-major-level, max-minor-level)  
experience-formula: 10*(1-Math.cos((level-1)*Math.PI/maxLevel/2))/(1-Math.cos(1*Math.PI/maxLevel/2))*0.606 #the total experience required to get to the level