backup: true # make a copy of playerTable in MineProfession/backup when saving the table
auto-save-cycle: 86400 # the cycle time of saving player data (unit: second) 
minor-require: 25 # the required level of major profession to have a minor profession
max-major-level: 100 # the maximum level of major profession
max-minor-level: 50 #the maximum level of minor profession
drop-replace:
   IRON_ORE: IRON_INGOT
   GOLD_ORE: GOLD_INGOT