backup: true # make a copy of playerTable in MineProfession/backup when saving the table
auto-save-cycle: 86400 # the cycle time of saving player data (unit: second) 
minor-require: 30 # the required level of major profession to have a minor profession
max-major-level: 85 # the maximum level of major profession
max-minor-level: 85 #the maximum level of minor profession
track-placement: [LOG, LEAVES, PUMPKIN, MELON_BLOCK, SUGAR_CANE_BLOCK, CLAY, IRON_ORE, GOLD_ORE]